### ISSUE TITLE
Update language selector and add Italian translation

### ISSUE THREAD

**Issue by sabas** [maphubs/maphubs#185]
Perhaps the language selector needs to be reworked to show all the languages (now 4, but in the future...)

**Comment by kriscarle** [comment]
@sabas Yes, need to rework the language selector as a drop-down, which is what keeps slowing me down on this...  Thanks for the reminder, I need to get the Italian translation up!

**Comment by kriscarle** [comment]
@sabas I went ahead and did this, should go live in production sometime latest this week, I'll let you know

Unfortunately, I did discover that the Mapbox base maps don't support Italian so the map labels for countries, cities, etc. will stay in English. https://www.mapbox.com/vector-tiles/mapbox-streets-v7/ Maybe we can petition Mapbox to add Italian :)

![image](https://cloud.githubusercontent.com/assets/2431570/16213669/44a7e57c-371f-11e6-963d-c433276067d8.png)

**Comment by sabas** [comment]
Awesome work!
